export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_BINHLUAN = 'FETCH_BINHLUAN';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_BINHLUAN = 'ADD_BINHLUAN'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'; 
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';

export const UPDATE_DONHANG ='UPDATE_DONHANG';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const SEARCH = 'SEARCH';
export const FILTER_TABLE = 'FILTER_TABLE';
export const UPDATE_BINHLUAN ='UPDATE_BINHLUAN';
export const FETCH_DONHANG = 'FETCH_DONHANG';
export const DELETE_DONHANG = 'DELETE_DONHANG'; 